[tool.poetry]
name = "lookyloo-testing"
version = "0.1.0"
description = "Simple webserver for testing lookyloo"
authors = ["Raphaël Vinot <raphael@lookyloo.eu>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
Flask = "^2.3.2"
Bootstrap-Flask = "^2.2.0"
ip2geotools = "^0.1.6"
gunicorn = "^20.1.0"
lxml = "^4.9.2"
gitpython = "^3.1.31"
flask-httpauth = "^4.8.0"
flask-wtf = "^1.1.1"

[tool.poetry.dev-dependencies]
mypy = "^1.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
