[tool.poetry]
name = "lookyloo-testing"
version = "0.1.0"
description = "Simple webserver for testing lookyloo"
authors = ["Raphaël Vinot <raphael@lookyloo.eu>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
Flask = "^2.3.3"
Bootstrap-Flask = "^2.3.0"
ip2geotools = "^0.1.6"
gunicorn = "^21.2.0"
lxml = "^4.9.3"
gitpython = "^3.1.37"
flask-httpauth = "^4.8.0"
flask-wtf = "^1.2.1"

[tool.poetry.dev-dependencies]
mypy = "^1.5.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
