[tool.poetry]
name = "lookyloo-testing"
version = "0.1.0"
description = "Simple webserver for testing lookyloo"
authors = ["Raphaël Vinot <raphael@lookyloo.eu>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
Flask = "^3.0.3"
Bootstrap-Flask = "^2.4.0"
ip2geotools = "^0.1.6"
gunicorn = "^22.0.0"
lxml = "^5.2.1"
gitpython = "^3.1.43"
flask-httpauth = "^4.8.0"
flask-wtf = "^1.2.1"

[tool.poetry.dev-dependencies]
mypy = "^1.9.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
